### ISSUE TITLE
Better way to connect busmaster pins

### ISSUE THREAD

**Issue by hdznrrd** [shackspace/hgg#20]
The pin header is kind of nasty. Look into using different means to connect the bus master PCB to the backplane

**Comment by hdznrrd** [comment]
Possibility: use larger PCIe plug for bus master

Pro:
- tons of room till we hit PCIe 16x

Con:
- PCB will be larger requiring a eagle license
- if we pick PCIe 8x we'll block pins for a future design where modules would require more pins themselves

**Comment by armin-bauer** [comment]
I think it's 10 pins so 5x2 if both sides are used. How about using a card-edge-connector once more. we might just place it where the pin header is now and move the connector on friendship to where the edge is. We could use something looking like xt-bus just with a shorter edge or even use pin headers with 1.25 width.

**Comment by hdznrrd** [comment]
using a PCIe 1x connector?
